// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpwfpoKe9h5ocRsZT4M5-ehl4SwjCMYGQ',
    appId: '1:817017672597:web:f81a72b6a82826f2025c9c',
    messagingSenderId: '817017672597',
    projectId: 'arsipku-eb7e6',
    authDomain: 'arsipku-eb7e6.firebaseapp.com',
    storageBucket: 'arsipku-eb7e6.firebasestorage.app',
    measurementId: 'G-LR28G5Y0TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfggKxWctp8aGSaln4dPCRasn3cXIPqxw',
    appId: '1:817017672597:android:ad25ca3e3a2c68a9025c9c',
    messagingSenderId: '817017672597',
    projectId: 'arsipku-eb7e6',
    storageBucket: 'arsipku-eb7e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6XjAYbB9Tczjg-5OFFfo6Yd75Zx46lnI',
    appId: '1:817017672597:ios:a79e29cde223f9a0025c9c',
    messagingSenderId: '817017672597',
    projectId: 'arsipku-eb7e6',
    storageBucket: 'arsipku-eb7e6.firebasestorage.app',
    androidClientId: '817017672597-cnsi43m5dlmuf2cvo6gh6gu7f04umh6h.apps.googleusercontent.com',
    iosClientId: '817017672597-9f02kk5e52784et1hvhtkdbtinmdv04o.apps.googleusercontent.com',
    iosBundleId: 'com.example.arsipku',
  );
}
